// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB7xjfRlkVM-lN2OTmwUeMWWZDFF2o8js',
    appId: '1:652475472599:web:8dd212a8e356f9f3c4ee92',
    messagingSenderId: '652475472599',
    projectId: 'auth-project-45e9c',
    authDomain: 'auth-project-45e9c.firebaseapp.com',
    storageBucket: 'auth-project-45e9c.appspot.com',
    measurementId: 'G-Z72FFV3XME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjUYGSyqYytQfuLuV6DZ80chLw7p8NTj0',
    appId: '1:652475472599:android:bc99945b80fc8a14c4ee92',
    messagingSenderId: '652475472599',
    projectId: 'auth-project-45e9c',
    storageBucket: 'auth-project-45e9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtlc56YT1vusJZQf_TyZRbbYoTQFQDd3M',
    appId: '1:652475472599:ios:83f1d2d79c7065ccc4ee92',
    messagingSenderId: '652475472599',
    projectId: 'auth-project-45e9c',
    storageBucket: 'auth-project-45e9c.appspot.com',
    iosBundleId: 'com.example.finaldeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtlc56YT1vusJZQf_TyZRbbYoTQFQDd3M',
    appId: '1:652475472599:ios:138abc50b76a5ec8c4ee92',
    messagingSenderId: '652475472599',
    projectId: 'auth-project-45e9c',
    storageBucket: 'auth-project-45e9c.appspot.com',
    iosBundleId: 'com.example.finaldeal.RunnerTests',
  );
}
